lr: 0.0001
batch_size: 1024
num_epochs: 200
coords: "/workspace7/fast_folders_cgnet/multiple_prot/data/cln_coords.npy"
forces: "deltaforces.npy"
embeddings: "cln_embeddings.npy"
log_dir: train_light
label: forces
derivative: forces
gpus: [0]
distributed_backend: dp
num_nodes: 1
eval_interval: 1
test_interval: 1
save_interval: 1
seed: 1
progress: True
val_ratio: 0.05
test_ratio: 0.1
num_workers: 8
num_filters: 128
num_gaussians: 150
num_interactions: 3
max_z: 100
cutoff: 9
lr_patience: 4
lr_min: 1.e-06
lr_factor: 0.8
